export const MIN_CUSTOMER_NAME_LENGTH = 2;
export const MAX_CUSTOMER_NAME_LENGTH = 120;
export const MAX_ORDER_ITEM_QUANTITY = 20;
export const MAX_ITEM_OBSERVATION_LENGTH = 300;
export const MAX_ORDER_OBSERVATION_LENGTH = 500;
